---
- hosts: all
  become: yes
  environment:
    KUBECONFIG: "{{ kubeconfig_env }}"

  pre_tasks:
  
    - name: Create kubeconfig files
      ansible.builtin.copy:
        dest: "{{ index }}.yml"
        content: |
          {{ item | b64decode }}
      loop: "{{ kubeconfigs_b64.split(',') }}"
      loop_control:
        index_var: index
      no_log: true  
      
    - name: Get all kubernetes cluster contexts
      command: |
        kubectl config get-contexts
      register: contexts
      
    - name: Show all kubernetes cluster contexts
      debug: var=contexts.stdout  

  tasks:
    - name: Get namespace files to deploy
      ansible.builtin.find:
        paths: /home/runner/work/kubernetes_multicluster/kubernetes_multicluster/terraform/ansible/applications
        file_type: file
        recurse: yes
        patterns: 'namespace.yml'
      register: namespace_files

    - name: Deploy namespaces
      shell: "kubectl --context='{{ item[1] }}' apply -f {{ item[0].path }}"
      with_nested: 
        - "{{ namespace_files.files }}"
        - "{{ clusters_name.split(',') }}"

    - name: Get app files to deploy
      ansible.builtin.find:
        paths: /home/runner/work/kubernetes_multicluster/kubernetes_multicluster/terraform/ansible/applications
        file_type: file
        recurse: yes
        patterns: '*.yml'
        exclude: 'namespace.yml'
      register: app_files

    - name: Deploy apps
      shell: "kubectl --context='{{ item[1] }}' apply -f {{ item[0].path }}"
      with_nested: 
        - "{{ app_files.files }}"
        - "{{ clusters_name.split(',') }}"