---
- hosts: all
  become: yes
  
  pre_tasks:
  
    - name: Install step-cli
      ansible.builtin.package:
        name: step
        state: present
  
  tasks:
  
    - name: Create kubernetes cluster contexts
      command:  "kubectl config set-context {{ item }} --kubeconfig='.{{ item }}.yml'"
      with_items: "{{ clusters_name.split(', ') }}"
      register: configurecontexts

    - name: Show all kubernetes cluster contexts
      debug: var=configurecontexts.stdout

    - name: Get all kubernetes cluster contexts
      command:  "kubectl config get-contexts"
      register: contexts
      
    - name: Show all kubernetes cluster contexts
      debug: var=contexts.stdout

    - name: Generate Linkerd certificates
      command: "xhost +local: && step certificate create root.linkerd.cluster.local root.crt root.key --profile root-ca --no-password --insecure"

    - name: Generate Linkerd issuer credentials certificates
      command: "step certificate create identity.linkerd.cluster.local issuer.crt issuer.key --profile intermediate-ca --not-after 8760h --no-password --insecure --ca root.crt --ca-key root.key"

    - name: Install Linkerd in each cluster
      command: "linkerd install --identity-trust-anchors-file root.crt --identity-issuer-certificate-file issuer.crt --identity-issuer-key-file issuer.key | kubectl --context={{ item }} apply -f -"
      with_items: "{{ clusters_name.split(', ') }}"
      
