---
- hosts: all
  serial: 1
  become: yes
  environment:
    KUBECONFIG: "{{ kubeconfig_env }}"
  
  pre_tasks:
  
    - name: Create kubeconfig files
      ansible.builtin.copy:
        dest: "{{ index }}.yml"
        content: |
          {{ item | b64decode }}
      loop: "{{ kubeconfigs_b64.split(',') }}"
      loop_control:
        index_var: index
      no_log: true  
      
    - name: Get all kubernetes cluster contexts
      command: |
        kubectl config get-contexts
      register: contexts
      
    - name: Show all kubernetes cluster contexts
      debug: var=contexts.stdout
  
  tasks:
  
    - name: Generate Linkerd certificates
      command: "step certificate create root.linkerd.cluster.local root.crt root.key --profile root-ca --no-password --insecure"

    - name: Generate Linkerd issuer credentials certificates
      command: "step certificate create identity.linkerd.cluster.local issuer.crt issuer.key --profile intermediate-ca --not-after 8760h --no-password --insecure --ca root.crt --ca-key root.key"

    - name: Install Linkerd in each cluster
      shell: "/home/runner/.linkerd2/bin/linkerd install --identity-trust-anchors-file root.crt --identity-issuer-certificate-file issuer.crt --identity-issuer-key-file issuer.key --context='{{ item }}' | kubectl --context='{{ item }}' apply -f -"
      with_items: "{{ clusters_name.split(',') }}"
      
