---
- hosts: all
  become: yes
  
  tasks:
  
    - name: Create kubernetes cluster contexts
      command:  "kubectl config set-context {{ item }} --kubeconfig='.{{ item }}.yml'"
      changed_when: False
      with_items: "{{ clusters_name.split(',') }}"

    - name: Show kubernetes cluster contexts
      command:  "kubectl config get-contexts"
      changed_when: False
