# This is a basic workflow to help you get started with Actions

name: Deploy Multicluster

env:
  RESOURCE_GROUP: "tfstate-rg"
  STORAGE_ACCOUNT: "tfstate-sa"
  CONTAINER_NAME: "tfstate-container"
  KEY: "main.tfstate"
  
on:
 # push:
    #branches: [ main ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1.4.2
        with:
          creds: ${{ secrets.APP_SECRET }}
          enable-AzPSSession: true

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Terraform init backend
        uses: ahmedig/terraform-azurerm-backend@v1
        with:
          azure_credentials: ${{ secrets.TF_AZURE_CREDENTIAL }}
          resource_group_name: ${{ env.RESOURCE_GROUP }}
          container_name: ${{ env.CONTAINER_NAME }}
          storage_account_name: ${{ env.STORAGE_ACCOUNT }}
          file_name: ${{ env.KEY }}
          tf_working_directory: ${{ GITHUB_WORKSPACE }}/terraform

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
