# This is a basic workflow to help you get started with Actions

name: Deploy Multicluster

env:
  RESOURCE_GROUP: "tfstate-rg"
  STORAGE_ACCOUNT: "tfstate-sa"
  CONTAINER_NAME: "tfstate-container"
  KEY: "main.tfstate"
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
 # push:
    #branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1.4.2
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.APP_SECRET }}
          # Set this value to true to enable Azure PowerShell Login in addition to Az CLI login
          enable-AzPSSession: true

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Terraform init backend
        uses: ahmedig/terraform-azurerm-backend@v1
        with:
          azure_credentials: ${{ secrets.TF_AZURE_CREDENTIAL }}
          # State file location - resource group name
          resource_group_name: ${{ env.RESOURCE_GROUP }}
          # State file location - container name
          container_name: ${{ env.CONTAINER_NAME }}
          # State file location - storage account name
          storage_account_name: ${{ env.STORAGE_ACCOUNT }}
          # State file location - file name
          file_name: ${{ env.KEY }}
          # Terraform working directory
          tf_working_directory: ${{ GITHUB_WORKSPACE }}/terraform

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
