# This is a basic workflow to help you get started with Actions

name: Deploy Multicluster

env:
  RESOURCE_GROUP: "tfstate-rg"
  STORAGE_ACCOUNT: "tfstatepfaccount"
  CONTAINER_NAME: "tfstate-container"
  KEY: "main.tfstate"
  APP_SECRET: ${{ secrets.AZURE_APP_SECRET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  
on:
#  push:
#    branches: [ main ]
#  schedule:
#    - cron: '10 * * * *'

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Replace tokens
        # You may pin to the exact commit or the version.
        # uses: cschleiden/replace-tokens@4f7e3d67f3ff2317ae650842145cdbaefba65189
        uses: cschleiden/replace-tokens@v1.1
        with:
          files: '["**/*"]'

      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          # Version range or exact version of Python to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: '3.x'

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest
          
      - name: Install kubectl
        uses: Azure/setup-kubectl@v2.1
        with:
          version: latest

      - name: Install Linkerd
        run: |
          curl --proto '=https' --tlsv1.2 -sSfL https://run.linkerd.io/install | sh
          linkerd version
        working-directory: ${{ github.workspace}}/terraform

      - name: Terraform init
        run: terraform init
        working-directory: ${{ github.workspace}}/terraform
        
      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ github.workspace}}/terraform
        
      - name: Manual Workflow Approval
        uses: trstringer/manual-approval@v1.5.0
        with:
          # Required approvers
          approvers: JoltLeo
          # Secret
          secret: ${{ github.TOKEN }}
          minimum-approvals: 1
          # The custom subtitle for the issue
          issue-title: "Check plan and Approve"
 
      - name: Terraform Apply
        run: terraform apply --auto-approve
        working-directory: ${{ github.workspace}}/terraform
        



      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
